/* Generated by Frama-C */
typedef unsigned char __u8;
typedef unsigned long long __u64;
typedef __u8 u8;
typedef __u64 u64;
typedef long __kernel_long_t;
typedef unsigned long __kernel_ulong_t;
typedef __kernel_ulong_t __kernel_size_t;
typedef __kernel_long_t __kernel_ssize_t;
typedef __kernel_size_t size_t;
typedef __kernel_ssize_t ssize_t;
struct word_at_a_time {
   unsigned long const one_bits ;
   unsigned long const high_bits ;
};
/* compiler builtin: 
   void __builtin_unreachable(void);   */
unsigned long strlen(char const *s);

/*@ requires dst_ok: \valid((char *)to + (0 .. len - 1));
    requires src_ok: \valid_read((char *)from + (0 .. len - 1));
    requires
      no_overlap:
        \separated(
          (char *)to + (0 .. len - 1), (char *)from + (0 .. len - 1)
          );
    ensures
      copied:
        ∀ ℤ i;
          0 ≤ i < \old(len) ⇒
          *((char *)\old(to) + i) ≡ *((char *)\old(from) + i);
    ensures \result ≡ \old(to);
    assigns *((char *)to + (0 .. len - 1)), \result;
    assigns *((char *)to + (0 .. len - 1))
      \from *((char *)from + (0 .. len - 1));
    assigns \result \from to;
 */
extern void *memcpy(void *to, void const *from, size_t len);

extern unsigned char const _ctype[];

__inline static unsigned char __attribute__((__gnu_inline__)) __tolower
(unsigned char c) __attribute__((__unused__, __no_instrument_function__));
__inline static unsigned char __attribute__((__gnu_inline__)) __tolower
(unsigned char c)
{
  if (((int)_ctype[(int)c] & 0x01) != 0) c = (unsigned char)((int)c - (
                                                             'A' - 'a'));
  return c;
}

int __attribute__((__externally_visible__)) memcmp(void const *cs,
                                                   void const *ct,
                                                   size_t count);

char *strcpy(char *dest, char const *src);

char *strcat(char *dest, char const *src);

int strcmp(char const *cs, char const *ct);

ssize_t sized_strscpy(char *dest, char const *src, size_t count);

char *strncat(char *dest, char const *src, __kernel_size_t count);

size_t strlcat(char *dest, char const *src, __kernel_size_t count);

int strncmp(char const *cs, char const *ct, __kernel_size_t count);

int strcasecmp(char const *s1, char const *s2);

int strncasecmp(char const *s1, char const *s2, size_t len);

char *strchr(char const *s, int c);

char *strchrnul(char const *s, int c);

char *strnchrnul(char const *s, size_t count, int c);

char *strnchr(char const *s, size_t count, int c);

char *strrchr(char const *s, int c);

char *strstr(char const *s1, char const *s2);

char *strnstr(char const *s1, char const *s2, size_t len);

__kernel_size_t strnlen(char const *s, __kernel_size_t count);

char *strpbrk(char const *cs, char const *ct);

char *strsep(char **s, char const *ct);

__kernel_size_t strspn(char const *s, char const *accept);

__kernel_size_t strcspn(char const *s, char const *reject);

void *memscan(void *addr, int c, __kernel_size_t size);

int bcmp(void const *a, void const *b, __kernel_size_t len);

void *memchr(void const *s, int c, __kernel_size_t n);

void *memchr_inv(void const *start, int c, size_t bytes);

__inline static unsigned long __attribute__((__gnu_inline__)) ( __attribute__((
__always_inline__)) variable__ffs)(unsigned long word) __attribute__((
__unused__, __no_instrument_function__, __const__));
__inline static unsigned long __attribute__((__gnu_inline__)) ( __attribute__((
__always_inline__)) variable__ffs)(unsigned long word)
{
  /*@ assigns word;
      assigns word \from word; */
  __asm__ ("tzcnt %1,%0" : "=r" (word) : "rm" (word));
  return word;
}

__inline static unsigned long __attribute__((__gnu_inline__)) has_zero
(unsigned long a, unsigned long *bits, struct word_at_a_time const *c) __attribute__((
__unused__, __no_instrument_function__));
__inline static unsigned long __attribute__((__gnu_inline__)) has_zero
(unsigned long a, unsigned long *bits, struct word_at_a_time const *c)
{
  unsigned long mask = ((a - c->one_bits) & ~ a) & c->high_bits;
  *bits = mask;
  return mask;
}

__inline static unsigned long __attribute__((__gnu_inline__)) prep_zero_mask
(unsigned long a, unsigned long bits, struct word_at_a_time const *c) __attribute__((
__unused__, __no_instrument_function__));
__inline static unsigned long __attribute__((__gnu_inline__)) prep_zero_mask
(unsigned long a, unsigned long bits, struct word_at_a_time const *c)
{
  return bits;
}

__inline static unsigned long __attribute__((__gnu_inline__)) zero_bytemask
(unsigned long bits) __attribute__((__unused__, __no_instrument_function__));
__inline static unsigned long __attribute__((__gnu_inline__)) zero_bytemask
(unsigned long bits)
{
  unsigned long __attribute__((__gnu_inline__)) __retres;
  bits = (bits - (unsigned long)1) & ~ bits;
  __retres = bits >> 7;
  return __retres;
}

__inline static unsigned long __attribute__((__gnu_inline__)) load_unaligned_zeropad
(void const *addr) __attribute__((__unused__, __no_instrument_function__));
__inline static unsigned long __attribute__((__gnu_inline__)) load_unaligned_zeropad
(void const *addr)
{
  unsigned long ret;
  /*@ assigns ret;
      assigns ret \from *((unsigned long *)addr); */
  __asm__ volatile (
    "1:\tmov %[mem], %[ret]\n"
    "2:\n"
    " .pushsection __ex_table, \"aM\", @progbits, 12\n"
    " .balign 4\n"
    " .long (1b) - .\n"
    " .long (2b) - .\n"
    " .long 20 \n"
    " .popsection\n"
    : [ret] "=r" (ret)
    : [mem] "m" (*((unsigned long *)addr))
    );
  return ret;
}

int strncasecmp(char const *s1, char const *s2, size_t len)
{
  int __retres;
  unsigned char c1;
  unsigned char c2;
  if (! len) {
    __retres = 0;
    goto return_label;
  }
  while (1) {
    {
      char const *tmp;
      char const *tmp_0;
      tmp = s1;
      s1 ++;
      c1 = (unsigned char)*tmp;
      tmp_0 = s2;
      s2 ++;
      c2 = (unsigned char)*tmp_0;
      if (! c1) break;
      else 
        if (! c2) break;
      if ((int)c1 == (int)c2) goto __Cont;
      c1 = __tolower(c1);
      c2 = __tolower(c2);
      if ((int)c1 != (int)c2) break;
    }
    __Cont: len --;
    if (! len) break;
  }
  __retres = (int)c1 - (int)c2;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strncasecmp_5 __attribute__((__used__,
                                                                  __section__(".discard.addressable"))) =
  (void *)(& strncasecmp);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strncasecmp: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strncasecmp ; .previous");
int strcasecmp(char const *s1, char const *s2)
{
  int __retres;
  int c1;
  int c2;
  while (1) {
    {
      unsigned char __attribute__((__gnu_inline__)) tmp_0;
      char const *tmp;
      unsigned char __attribute__((__gnu_inline__)) tmp_2;
      char const *tmp_1;
      tmp = s1;
      s1 ++;
      ;
      tmp_0 = __tolower((unsigned char)*tmp);
      c1 = (int)tmp_0;
      tmp_1 = s2;
      s2 ++;
      ;
      tmp_2 = __tolower((unsigned char)*tmp_1);
      c2 = (int)tmp_2;
    }
    if (c1 == c2) {
      if (! (c1 != 0)) break;
    }
    else break;
  }
  __retres = c1 - c2;
  return __retres;
}

static void *__UNIQUE_ID_addressable_strcasecmp_6 __attribute__((__used__,
                                                                 __section__(".discard.addressable"))) =
  (void *)(& strcasecmp);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strcasecmp: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strcasecmp ; .previous");
char *strcpy(char *dest, char const *src)
{
  char *tmp = dest;
  while (1) {
    char *tmp_0;
    char const *tmp_2;
    char tmp_1;
    tmp_0 = dest;
    dest ++;
    tmp_2 = src;
    src ++;
    tmp_1 = *tmp_2;
    *tmp_0 = tmp_1;
    if (! ((int)tmp_1 != '\000')) break;
  }
  return tmp;
}

static void *__UNIQUE_ID_addressable_strcpy_7 __attribute__((__used__,
                                                             __section__(".discard.addressable"))) =
  (void *)(& strcpy);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strcpy: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strcpy ; .previous");
ssize_t sized_strscpy(char *dest, char const *src, size_t count)
{
  ssize_t __retres;
  long tmp_4;
  struct word_at_a_time const constants =
    {.one_bits = (~ 0ul / (unsigned long)0xff) * (unsigned long)0x01,
     .high_bits = (~ 0ul / (unsigned long)0xff) * (unsigned long)0x80};
  size_t max = count;
  long res = (long)0;
  if (count == (size_t)0) {
    __retres = (ssize_t)(-7);
    goto return_label;
  }
  else {
    int tmp;
    {
      int __ret_warn_on = ! (! (count > (size_t)((int)(~ 0U >> 1))));
      tmp = (long)(! (! __ret_warn_on));
    }
    if (tmp) {
      __retres = (ssize_t)(-7);
      goto return_label;
    }
  }
  while (max >= sizeof(unsigned long)) {
    unsigned long c;
    unsigned long data;
    unsigned long __attribute__((__gnu_inline__)) tmp_3;
    c = load_unaligned_zeropad((void const *)(src + res));
    tmp_3 = has_zero(c,& data,& constants);
    if (tmp_3) {
      unsigned long __attribute__((__gnu_inline__)) tmp_0;
      unsigned long __attribute__((__gnu_inline__)) tmp_2;
      data = prep_zero_mask(c,data,& constants);
      data = data;
      tmp_0 = zero_bytemask(data);
      *((unsigned long *)(dest + res)) = c & tmp_0;
      tmp_2 = variable__ffs(data);
      ;
      __retres = (ssize_t)((unsigned long __attribute__((__gnu_inline__)))res + (
                           tmp_2 >> 3));
      goto return_label;
    }
    count -= sizeof(unsigned long);
    if ((long)(! (! (! count)))) {
      c &= ~ 0ul >> 8;
      *((unsigned long *)(dest + res)) = c;
      __retres = (ssize_t)(-7);
      goto return_label;
    }
    *((unsigned long *)(dest + res)) = c;
    res = (long)((unsigned long)res + sizeof(unsigned long));
    max -= sizeof(unsigned long);
  }
  while (count > (size_t)1) {
    char c_0;
    c_0 = *(src + res);
    *(dest + res) = c_0;
    if (! c_0) {
      __retres = res;
      goto return_label;
    }
    res ++;
    count --;
  }
  *(dest + res) = (char)'\000';
  if (*(src + res)) tmp_4 = (long)(-7); else tmp_4 = res;
  __retres = tmp_4;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_sized_strscpy_8 __attribute__((__used__,
                                                                    __section__(".discard.addressable"))) =
  (void *)(& sized_strscpy);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_sized_strscpy: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad sized_strscpy ; .previous");
char *stpcpy(char * restrict dest, char const * restrict src);

char *stpcpy(char * restrict dest, char const * restrict src)
{
  while (1) {
    char *tmp;
    char const *tmp_1;
    char tmp_0;
    tmp = dest;
    dest ++;
    tmp_1 = src;
    src ++;
    tmp_0 = *tmp_1;
    *tmp = tmp_0;
    if (! ((int)tmp_0 != '\000')) break;
  }
  dest --;
  return dest;
}

static void *__UNIQUE_ID_addressable_stpcpy_9 __attribute__((__used__,
                                                             __section__(".discard.addressable"))) =
  (void *)(& stpcpy);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_stpcpy: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad stpcpy ; .previous");
char *strcat(char *dest, char const *src)
{
  char *tmp = dest;
  while (*dest) dest ++;
  while (1) {
    char *tmp_0;
    char const *tmp_2;
    char tmp_1;
    tmp_0 = dest;
    dest ++;
    tmp_2 = src;
    src ++;
    tmp_1 = *tmp_2;
    *tmp_0 = tmp_1;
    if (! ((int)tmp_1 != '\000')) break;
  }
  return tmp;
}

static void *__UNIQUE_ID_addressable_strcat_10 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strcat);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strcat: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strcat ; .previous");
char *strncat(char *dest, char const *src, __kernel_size_t count)
{
  char *tmp = dest;
  if (count) {
    while (*dest) dest ++;
    while (1) {
      char *tmp_0;
      char const *tmp_2;
      char tmp_1;
      tmp_0 = dest;
      dest ++;
      tmp_2 = src;
      src ++;
      tmp_1 = *tmp_2;
      *tmp_0 = tmp_1;
      if (! ((int)tmp_1 != 0)) break;
      count --;
      if (count == (__kernel_size_t)0) {
        *dest = (char)'\000';
        break;
      }
    }
  }
  return tmp;
}

static void *__UNIQUE_ID_addressable_strncat_11 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strncat);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strncat: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strncat ; .previous");
/*@ requires count_pos: count ≥ 1;
    requires dest_writable: \valid(dest + (0 .. count - 1));
    requires
      dest_str: ∃ ℤ d; 0 ≤ d ∧ *(dest + d) ≡ 0 ∧ \valid_read(dest + (0 .. d));
    requires
      src_ok:
        ∃ ℤ n;
          0 ≤ n ∧ *(src + n) ≡ 0 ∧ \valid_read(src + (0 .. n)) ∧
          \separated(dest + (0 .. count - 1), src + (0 .. n));
    ensures terminated: ∃ ℤ e; 0 ≤ e < \old(count) ∧ *(\old(dest) + e) ≡ 0;
    ensures
      naive_no_truncation:
        ∃ ℤ e; 0 ≤ e < \old(count) ∧ *(\old(dest) + e) ≡ 0 ∧ e ≡ \result;
    assigns *(dest + (0 .. count - 1));
 */
size_t strlcat(char *dest, char const *src, __kernel_size_t count)
{
  size_t dsize = strlen((char const *)dest);
  size_t len = strlen(src);
  size_t res = dsize + len;
  if ((long)(! (! (dsize >= count)))) {
    __asm__ volatile (" ud2 ");
    __builtin_unreachable();
  }
  /*@ assert guard_passed: dsize < count; */ ;
  dest += dsize;
  count -= dsize;
  if (len >= count) len = count - (__kernel_size_t)1;
  memcpy((void *)dest,(void const *)src,len);
  *(dest + len) = (char)0;
  return res;
}

static void *__UNIQUE_ID_addressable_strlcat_12 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strlcat);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strlcat: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strlcat ; .previous");
int strcmp(char const *cs, char const *ct)
{
  int __retres;
  unsigned char c1;
  unsigned char c2;
  while (1) {
    char const *tmp;
    char const *tmp_0;
    tmp = cs;
    cs ++;
    c1 = (unsigned char)*tmp;
    tmp_0 = ct;
    ct ++;
    c2 = (unsigned char)*tmp_0;
    if ((int)c1 != (int)c2) {
      int tmp_1;
      if ((int)c1 < (int)c2) tmp_1 = -1; else tmp_1 = 1;
      __retres = tmp_1;
      goto return_label;
    }
    if (! c1) break;
  }
  __retres = 0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strcmp_13 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strcmp);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strcmp: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strcmp ; .previous");
int strncmp(char const *cs, char const *ct, __kernel_size_t count)
{
  int __retres;
  unsigned char c1;
  unsigned char c2;
  while (count) {
    char const *tmp;
    char const *tmp_0;
    tmp = cs;
    cs ++;
    c1 = (unsigned char)*tmp;
    tmp_0 = ct;
    ct ++;
    c2 = (unsigned char)*tmp_0;
    if ((int)c1 != (int)c2) {
      int tmp_1;
      if ((int)c1 < (int)c2) tmp_1 = -1; else tmp_1 = 1;
      __retres = tmp_1;
      goto return_label;
    }
    if (! c1) break;
    count --;
  }
  __retres = 0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strncmp_14 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strncmp);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strncmp: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strncmp ; .previous");
char *strchr(char const *s, int c)
{
  char *__retres;
  while ((int)*s != (int)((char)c)) {
    if ((int)*s == '\000') {
      __retres = (char *)0;
      goto return_label;
    }
    s ++;
  }
  __retres = (char *)s;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strchr_15 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strchr);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strchr: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strchr ; .previous");
char *strchrnul(char const *s, int c)
{
  char *__retres;
  while (1) {
    if (*s) {
      if (! ((int)*s != (int)((char)c))) break;
    }
    else break;
    s ++;
  }
  __retres = (char *)s;
  return __retres;
}

static void *__UNIQUE_ID_addressable_strchrnul_16 __attribute__((__used__,
                                                                 __section__(".discard.addressable"))) =
  (void *)(& strchrnul);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strchrnul: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strchrnul ; .previous");
char *strnchrnul(char const *s, size_t count, int c)
{
  char *__retres;
  while (1) {
    size_t tmp;
    tmp = count;
    count --;
    ;
    if (tmp) 
      if (*s) {
        if (! ((int)*s != (int)((char)c))) break;
      }
      else break;
    else break;
    s ++;
  }
  __retres = (char *)s;
  return __retres;
}

char *strrchr(char const *s, int c)
{
  char *__retres;
  char const *last = (char const *)0;
  while (1) {
    char const *tmp;
    if ((int)*s == (int)((char)c)) last = s;
    tmp = s;
    s ++;
    ;
    if (! *tmp) break;
  }
  __retres = (char *)last;
  return __retres;
}

static void *__UNIQUE_ID_addressable_strrchr_17 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strrchr);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strrchr: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strrchr ; .previous");
/*@ requires readable: count > 0 ⇒ \valid_read(s + (0 .. count - 1));
    ensures
      found_in_range:
        \result ≢ \null ⇒
        \old(s) ≤ \result < \old(s) + \old(count) ∧ *\result ≡ (char)\old(c);
    ensures
      found_first:
        \result ≢ \null ⇒
        (∀ ℤ j;
           0 ≤ j < \result - \old(s) ⇒
           *(\old(s) + j) ≢ (char)\old(c) ∧ *(\old(s) + j) ≢ 0);
    ensures
      null_means_absent:
        \result ≡ \null ⇒
        (∃ ℤ k;
           0 ≤ k ≤ \old(count) ∧
           (∀ ℤ j;
              0 ≤ j < k ⇒ *(\old(s) + j) ≢ (char)\old(c) ∧ *(\old(s) + j) ≢ 0) ∧
           (k ≡ \old(count) ∨
            (*(\old(s) + k) ≢ (char)\old(c) ∧ *(\old(s) + k) ≡ 0)));
    assigns \nothing;
 */
char *strnchr(char const *s, size_t count, int c)
{
  char *__retres;
  /*@ loop invariant same_base: \base_addr(s) ≡ \base_addr(\at(s,Pre));
      loop invariant in_range: \at(s,Pre) ≤ s ≤ \at(s,Pre) + \at(count,Pre);
      loop invariant scanned: 0 ≤ s - \at(s,Pre) ≤ \at(count,Pre);
      loop invariant countdown: count ≡ \at(count,Pre) - (s - \at(s,Pre));
      loop invariant
        not_yet:
          ∀ ℤ j;
            0 ≤ j < s - \at(s,Pre) ⇒
            *(\at(s,Pre) + j) ≢ (char)c ∧ *(\at(s,Pre) + j) ≢ 0;
      loop assigns count, s;
      loop variant count;
  */
  while (1) {
    size_t tmp_0;
    tmp_0 = count;
    count --;
    ;
    if (! tmp_0) break;
    {
      char const *tmp;
      if ((int)*s == (int)((char)c)) {
        __retres = (char *)s;
        goto return_label;
      }
      tmp = s;
      s ++;
      ;
      if ((int)*tmp == '\000') {
        /*@
        assert
          nul_idx:
            0 ≤ (s - \at(s,Pre)) - 1 < \at(count,Pre) ∧
            *(\at(s,Pre) + ((s - \at(s,Pre)) - 1)) ≡ 0 ∧
            *(\at(s,Pre) + ((s - \at(s,Pre)) - 1)) ≢ (char)c ∧
            (∀ ℤ j;
               0 ≤ j < (s - \at(s,Pre)) - 1 ⇒
               *(\at(s,Pre) + j) ≢ (char)c ∧ *(\at(s,Pre) + j) ≢ 0);
         */
        ;
        break;
      }
    }
  }
  /*@
  assert
    exit_witness:
      ∃ ℤ k;
        0 ≤ k ≤ \at(count,Pre) ∧
        (∀ ℤ j;
           0 ≤ j < k ⇒ *(\at(s,Pre) + j) ≢ (char)c ∧ *(\at(s,Pre) + j) ≢ 0) ∧
        (k ≡ \at(count,Pre) ∨
         (*(\at(s,Pre) + k) ≢ (char)c ∧ *(\at(s,Pre) + k) ≡ 0));
   */
  ;
  __retres = (char *)0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strnchr_18 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strnchr);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strnchr: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strnchr ; .previous");
/*@ requires
      valid_string: ∃ ℤ n; 0 ≤ n ∧ *(s + n) ≡ 0 ∧ \valid_read(s + (0 .. n));
    ensures nul_at_result: *(\old(s) + \result) ≡ 0;
    ensures first_nul: ∀ ℤ i; 0 ≤ i < \result ⇒ *(\old(s) + i) ≢ 0;
    assigns \nothing;
 */
unsigned long strlen(char const *s)
{
  unsigned long __retres;
  char const *sc;
  sc = s;
  while ((int)*sc != '\000') sc ++;
  __retres = (unsigned long)(sc - s);
  return __retres;
}

static void *__UNIQUE_ID_addressable_strlen_19 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strlen);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strlen: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strlen ; .previous");
__kernel_size_t strnlen(char const *s, __kernel_size_t count)
{
  __kernel_size_t __retres;
  char const *sc;
  sc = s;
  while (1) {
    __kernel_size_t tmp;
    tmp = count;
    count --;
    ;
    if (tmp) {
      if (! ((int)*sc != '\000')) break;
    }
    else break;
    sc ++;
  }
  __retres = (__kernel_size_t)(sc - s);
  return __retres;
}

static void *__UNIQUE_ID_addressable_strnlen_20 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strnlen);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strnlen: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strnlen ; .previous");
__kernel_size_t strspn(char const *s, char const *accept)
{
  __kernel_size_t __retres;
  char const *p;
  p = s;
  while ((int)*p != '\000') {
    {
      char *tmp;
      tmp = strchr(accept,(int)*p);
      if (! tmp) break;
    }
    p ++;
  }
  __retres = (__kernel_size_t)(p - s);
  return __retres;
}

static void *__UNIQUE_ID_addressable_strspn_21 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strspn);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strspn: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strspn ; .previous");
__kernel_size_t strcspn(char const *s, char const *reject)
{
  __kernel_size_t __retres;
  char const *p;
  p = s;
  while ((int)*p != '\000') {
    {
      char *tmp;
      tmp = strchr(reject,(int)*p);
      if (tmp) break;
    }
    p ++;
  }
  __retres = (__kernel_size_t)(p - s);
  return __retres;
}

static void *__UNIQUE_ID_addressable_strcspn_22 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strcspn);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strcspn: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strcspn ; .previous");
char *strpbrk(char const *cs, char const *ct)
{
  char *__retres;
  char const *sc;
  sc = cs;
  while ((int)*sc != '\000') {
    {
      char *tmp;
      tmp = strchr(ct,(int)*sc);
      if (tmp) {
        __retres = (char *)sc;
        goto return_label;
      }
    }
    sc ++;
  }
  __retres = (char *)0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strpbrk_23 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strpbrk);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strpbrk: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strpbrk ; .previous");
char *strsep(char **s, char const *ct)
{
  char *__retres;
  char *end;
  char *sbegin = *s;
  if (sbegin == (char *)0) {
    __retres = (char *)0;
    goto return_label;
  }
  end = strpbrk((char const *)sbegin,ct);
  if (end) {
    char *tmp;
    tmp = end;
    end ++;
    *tmp = (char)'\000';
  }
  *s = end;
  __retres = sbegin;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strsep_24 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strsep);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strsep: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strsep ; .previous");
int __attribute__((__externally_visible__)) memcmp(void const *cs,
                                                   void const *ct,
                                                   size_t count)
{
  unsigned char const *su1;
  unsigned char const *su2;
  int res = 0;
  if (count >= sizeof(unsigned long)) {
    unsigned long const *u1 = (unsigned long const *)cs;
    unsigned long const *u2 = (unsigned long const *)ct;
    while (1) {
      {
        unsigned long tmp;
        unsigned long tmp_0;
        {
          unsigned long __get_unaligned_val;
          unsigned long *__get_unaligned_ctrl_type __attribute__((__unused__)) =
            (unsigned long *)0;
          memcpy((void *)(& __get_unaligned_val),(void const *)u1,
                 sizeof(__get_unaligned_val));
          tmp = __get_unaligned_val;
        }
        {
          unsigned long __get_unaligned_val_0;
          unsigned long *__get_unaligned_ctrl_type_0 __attribute__((__unused__)) =
            (unsigned long *)0;
          memcpy((void *)(& __get_unaligned_val_0),(void const *)u2,
                 sizeof(__get_unaligned_val_0));
          tmp_0 = __get_unaligned_val_0;
        }
        if (tmp != tmp_0) break;
        u1 ++;
        u2 ++;
        count -= sizeof(unsigned long);
      }
      if (! (count >= sizeof(unsigned long))) break;
    }
    cs = (void const *)u1;
    ct = (void const *)u2;
  }
  su1 = (unsigned char const *)cs;
  su2 = (unsigned char const *)ct;
  while ((size_t)0 < count) {
    res = (int)*su1 - (int)*su2;
    if (res != 0) break;
    su1 ++;
    su2 ++;
    count --;
  }
  return res;
}

static void *__UNIQUE_ID_addressable_memcmp_25 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& memcmp);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_memcmp: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad memcmp ; .previous");
int bcmp(void const *a, void const *b, __kernel_size_t len)
{
  int tmp;
  tmp = memcmp(a,b,len);
  return tmp;
}

static void *__UNIQUE_ID_addressable_bcmp_26 __attribute__((__used__,
                                                            __section__(".discard.addressable"))) =
  (void *)(& bcmp);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_bcmp: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad bcmp ; .previous");
void *memscan(void *addr, int c, __kernel_size_t size)
{
  void *__retres;
  unsigned char *p = (unsigned char *)addr;
  while (size) {
    if ((int)*p == (int)((unsigned char)c)) {
      __retres = (void *)p;
      goto return_label;
    }
    p ++;
    size --;
  }
  __retres = (void *)p;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_memscan_27 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& memscan);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_memscan: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad memscan ; .previous");
char *strstr(char const *s1, char const *s2)
{
  char *__retres;
  size_t l1;
  size_t l2;
  l2 = strlen(s2);
  if (! l2) {
    __retres = (char *)s1;
    goto return_label;
  }
  l1 = strlen(s1);
  while (l1 >= l2) {
    int __attribute__((__externally_visible__)) tmp;
    l1 --;
    tmp = memcmp((void const *)s1,(void const *)s2,l2);
    if (! tmp) {
      __retres = (char *)s1;
      goto return_label;
    }
    s1 ++;
  }
  __retres = (char *)0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strstr_28 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& strstr);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strstr: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strstr ; .previous");
char *strnstr(char const *s1, char const *s2, size_t len)
{
  char *__retres;
  size_t l2;
  l2 = strlen(s2);
  if (! l2) {
    __retres = (char *)s1;
    goto return_label;
  }
  while (len >= l2) {
    int __attribute__((__externally_visible__)) tmp;
    len --;
    tmp = memcmp((void const *)s1,(void const *)s2,l2);
    if (! tmp) {
      __retres = (char *)s1;
      goto return_label;
    }
    s1 ++;
  }
  __retres = (char *)0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_strnstr_29 __attribute__((__used__,
                                                               __section__(".discard.addressable"))) =
  (void *)(& strnstr);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_strnstr: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad strnstr ; .previous");
void *memchr(void const *s, int c, __kernel_size_t n)
{
  void *__retres;
  unsigned char const *p = (unsigned char const *)s;
  while (1) {
    __kernel_size_t tmp_0;
    tmp_0 = n;
    n --;
    ;
    if (! (tmp_0 != (__kernel_size_t)0)) break;
    {
      unsigned char const *tmp;
      tmp = p;
      p ++;
      ;
      if ((int)((unsigned char)c) == (int)*tmp) {
        __retres = (void *)(p - 1);
        goto return_label;
      }
    }
  }
  __retres = (void *)0;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_memchr_30 __attribute__((__used__,
                                                              __section__(".discard.addressable"))) =
  (void *)(& memchr);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_memchr: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad memchr ; .previous");
static void *check_bytes8(u8 const *start, u8 value, unsigned int bytes)
{
  void *__retres;
  while (bytes) {
    if ((int)*start != (int)value) {
      __retres = (void *)start;
      goto return_label;
    }
    start ++;
    bytes --;
  }
  __retres = (void *)0;
  return_label: return __retres;
}

void *memchr_inv(void const *start, int c, size_t bytes)
{
  void *__retres;
  u64 value64;
  unsigned int words;
  unsigned int prefix;
  void *tmp_1;
  u8 value = (u8)c;
  if (bytes <= (size_t)16) {
    void *tmp;
    tmp = check_bytes8((u8 const *)start,value,(unsigned int)bytes);
    __retres = tmp;
    goto return_label;
  }
  value64 = (u64)value;
  value64 *= 0x0101010101010101ULL;
  prefix = (unsigned int)((unsigned long)start % (unsigned long)8);
  if (prefix) {
    u8 *r;
    prefix = (unsigned int)8 - prefix;
    r = (u8 *)check_bytes8((u8 const *)start,value,prefix);
    if (r) {
      __retres = (void *)r;
      goto return_label;
    }
    start += prefix;
    bytes -= (size_t)prefix;
  }
  words = (unsigned int)(bytes / (size_t)8);
  while (words) {
    if (*((u64 *)start) != value64) {
      void *tmp_0;
      tmp_0 = check_bytes8((u8 const *)start,value,(unsigned int)8);
      __retres = tmp_0;
      goto return_label;
    }
    start += 8;
    words --;
  }
  tmp_1 = check_bytes8((u8 const *)start,value,
                       (unsigned int)(bytes % (size_t)8));
  __retres = tmp_1;
  return_label: return __retres;
}

static void *__UNIQUE_ID_addressable_memchr_inv_31 __attribute__((__used__,
                                                                  __section__(".discard.addressable"))) =
  (void *)(& memchr_inv);
__asm__(".section \".export_symbol\",\"a\" ; __export_symbol_memchr_inv: ; .asciz \"\" ; .ascii \"\" \"\\0\" ; .balign 8 ; .quad memchr_inv ; .previous");

